#!/bin/sh
# Compile toutes les sources Java du dossier src/ vers bin/
mkdir -p bin
find src -name "*.java" > /tmp/sim_sources_$$.txt
javac -encoding UTF-8 -d bin @/tmp/sim_sources_$$.txt
STATUS=$?
rm -f /tmp/sim_sources_$$.txt
exit $STATUS
